In [6]:
import pandas as pd

In [5]:
big_check = pd.read_csv('20')

200kTags                  Testing Ground.ipynb      overwatch
200kTags.csv              Zero to Hero.ipynb        scrapy.cfg
200k_Top_Heroes.csv       csv testing.ipynb         tagnames.csv
200k_Top_test1.csv        df_comp_elim_permin.csv
Test_top_Heroes.csv       heros_for_playerstop5.csv

In [15]:
df1 = pd.read_csv('heros_for_playerstop5.csv')
df2 = pd.read_csv('df_comp_elim_permin.csv').replace('#', '-')

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (1,2,5,8,9,12,13,14,15,16,17,20,24,25,26,27,28,29,30,33,34,38,40,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [16]:
df2.Battle_Tag = df2.Battle_Tag.apply(lambda x: x.replace('#','-'))

In [17]:
df2.dropna(axis=0, how='any', inplace=True)

In [18]:
df2.reset_index(drop=True)

,Battle_Tag,Level,Skill Rating,K/d Ratio,Ka/d Ratio,Win %,Kills per Game,Eliminations per Game,Damage per Game,Healing per Game,...,Most Offensive Assists,Most Objective Kills,Most Objective Time,Most Solo Kills,Most Time Spent On Fire,Cards,Medals,Gold Medals,Silver Medals,Bronze Medals
0,Morellio-1416,"2,999","1,297,591,865",1.48,2.26,50.7%,14.21,14.21,"5,237.64","2,307.95",...,0.0,29.0,7m 40s,22.0,5m 32s,43.0,276,72,100.0,104.0
1,Zinux-1251,422,"29,053,161",4.68,5.32,76.7%,33.84,33.84,"15,140.02","1,262.35",...,0.0,25.0,6m 20s,36.0,9m 10s,31.0,137,80,34.0,23.0
2,BluePillow-21338,625,"28,042,860",2.33,2.72,80.0%,25.33,25.33,"9,547.33",886.13,...,0.0,16.0,5m 6s,25.0,4m 39s,5.0,31,12,12.0,7.0
3,Miyuna-21516,57,"25,273,056",2.71,2.96,70.0%,22.80,22.80,"7,987.43",578.83,...,0.0,19.0,4m 21s,24.0,4m 51s,0.0,67,12,21.0,34.0
4,Mood-21538,459,"25,382,447",2.01,2.84,34.2%,18.66,18.66,"7,424.13","1,861.95",...,0.0,17.0,2m 33s,28.0,5m 23s,7.0,72,20,30.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1632,LOBBER-11224,141,"15,771,648",3.03,3.31,50.0%,23.40,23.40,"10,028.69",439.51,...,0.0,32.0,7m 46s,34.0,6m 50s,93.0,586,262,165.0,158.0
1633,Frisk-31639,161,"15,801,793",1.88,3.25,42.2%,16.69,16.69,"5,157.38","5,646.53",...,0.0,28.0,7m 33s,18.0,2m 52s,20.0,116,48,35.0,33.0
1634,Maple-21960,162,"15,802,094",2.47,6.32,58.3%,15.93,15.93,"4,760.17","7,293.20",...,0.0,22.0,4m 7s,17.0,4m 39s,17.0,132,30,72.0,30.0
1635,PKBlizzard-21364,92,"15,871,524",1.34,2.24,37.8%,14.32,14.32,"5,165.11","2,000.19",...,0.0,30.0,9m 5s,15.0,3m 36s,17.0,77,38,18.0,21.0
1636,Daaxyy-1605,328,"17,472,256",0.83,4.52,43.5%,6.57,6.57,"1,621.81","11,325.55",...,0.0,30.0,9m 34s,11.0,5m 35s,70.0,301,116,125.0,60.0

In [19]:
df1.shape

(1524, 6)

In [20]:
df2.shape

(1637, 46)

In [21]:
df1.head()

         Battle_Tag       Hero1      Hero2     Hero3        Hero4     Hero5
0     Morellio-1416       Mercy  Reinhardt     Orisa        Moira   Winston
1         Ne0x-2676       Genji   Doomfist    Tracer        Hanzo  Zenyatta
2      Miyuna-21516  Widowmaker  Reinhardt    Pharah        Genji     Hanzo
3  Hunter18112-1984   Reinhardt      Mercy     Hanzo        Lúcio     Orisa
4        Zinux-1251       Hanzo        Ana  Torbjörn  Soldier: 76     Lúcio

In [22]:
df2.columns

Index(['Battle_Tag', 'Level', 'Skill Rating', 'K/d Ratio', 'Ka/d Ratio',
       'Win %', 'Kills per Game', 'Eliminations per Game', 'Damage per Game',
       'Healing per Game', 'Eliminations per Min', 'Healing per Min',
       'Damage per Min', 'Solo Kills', 'Objective Kills', 'Final Blows',
       'Damage Done', 'Eliminations', 'Environmental Kills', 'Multi Kills',
       'Deaths', 'Environmental Deaths', 'Games Won', 'Games Played',
       'Time Spent On Fire', 'Objective Time', 'Time Played', 'Assists',
       'Healing Done', 'Defensive Assists', 'Offensive Assists',
       'Most Eliminations', 'Most Final Blows', 'Most Damage Done',
       'Most Healing', 'Most Defensive Assists', 'Most Offensive Assists',
       'Most Objective Kills', 'Most Objective Time', 'Most Solo Kills',
       'Most Time Spent On Fire', 'Cards', 'Medals', 'Gold Medals',
       'Silver Medals', 'Bronze Medals'],
      dtype='object')

In [23]:
df1a = df1.set_index('Battle_Tag')
df1a

,Hero1,Hero2,Hero3,Hero4,Hero5
Battle_Tag,,,,,
Morellio-1416,Mercy,Reinhardt,Orisa,Moira,Winston
Ne0x-2676,Genji,Doomfist,Tracer,Hanzo,Zenyatta
Miyuna-21516,Widowmaker,Reinhardt,Pharah,Genji,Hanzo
Hunter18112-1984,Reinhardt,Mercy,Hanzo,Lúcio,Orisa
Zinux-1251,Hanzo,Ana,Torbjörn,Soldier: 76,Lúcio
...,...,...,...,...,...
Alpha2Omega-11700,Lúcio,Sigma,Moira,Reinhardt,D.Va
Kyfra-1768,Zenyatta,Tracer,Soldier: 76,Mercy,Moira
LOBBER-11224,Roadhog,Soldier: 76,Ashe,Junkrat,Genji
PKBlizzard-21364,Lúcio,Moira,Mercy,Orisa,Reinhardt
Daaxyy-1605,Moira,Sombra,Ana,Mercy,McCree

In [24]:
df = df2.join(df1a, on='Battle_Tag')
df

,Battle_Tag,Level,Skill Rating,K/d Ratio,Ka/d Ratio,Win %,Kills per Game,Eliminations per Game,Damage per Game,Healing per Game,...,Cards,Medals,Gold Medals,Silver Medals,Bronze Medals,Hero1,Hero2,Hero3,Hero4,Hero5
0,Morellio-1416,"2,999","1,297,591,865",1.48,2.26,50.7%,14.21,14.21,"5,237.64","2,307.95",...,43.0,276,72,100.0,104.0,Mercy,Reinhardt,Orisa,Moira,Winston
1,Zinux-1251,422,"29,053,161",4.68,5.32,76.7%,33.84,33.84,"15,140.02","1,262.35",...,31.0,137,80,34.0,23.0,Hanzo,Ana,Torbjörn,Soldier: 76,Lúcio
2,BluePillow-21338,625,"28,042,860",2.33,2.72,80.0%,25.33,25.33,"9,547.33",886.13,...,5.0,31,12,12.0,7.0,Hanzo,Genji,Widowmaker,McCree,Tracer
3,Miyuna-21516,57,"25,273,056",2.71,2.96,70.0%,22.80,22.80,"7,987.43",578.83,...,0.0,67,12,21.0,34.0,Widowmaker,Reinhardt,Pharah,Genji,Hanzo
4,Mood-21538,459,"25,382,447",2.01,2.84,34.2%,18.66,18.66,"7,424.13","1,861.95",...,7.0,72,20,30.0,22.0,Widowmaker,Tracer,Hanzo,Ana,Zenyatta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2722,LOBBER-11224,141,"15,771,648",3.03,3.31,50.0%,23.40,23.40,"10,028.69",439.51,...,93.0,586,262,165.0,158.0,Roadhog,Soldier: 76,Ashe,Junkrat,Genji
2725,Frisk-31639,161,"15,801,793",1.88,3.25,42.2%,16.69,16.69,"5,157.38","5,646.53",...,20.0,116,48,35.0,33.0,NaN,NaN,NaN,NaN,NaN
2728,Maple-21960,162,"15,802,094",2.47,6.32,58.3%,15.93,15.93,"4,760.17","7,293.20",...,17.0,132,30,72.0,30.0,NaN,NaN,NaN,NaN,NaN
2731,PKBlizzard-21364,92,"15,871,524",1.34,2.24,37.8%,14.32,14.32,"5,165.11","2,000.19",...,17.0,77,38,18.0,21.0,Lúcio,Moira,Mercy,Orisa,Reinhardt
2743,Daaxyy-1605,328,"17,472,256",0.83,4.52,43.5%,6.57,6.57,"1,621.81","11,325.55",...,70.0,301,116,125.0,60.0,Moira,Sombra,Ana,Mercy,McCree

In [28]:
df.dropna(axis=0, how='any', inplace=True)

In [29]:
df.isnull().sum()

Battle_Tag                 0
Level                      0
Skill Rating               0
K/d Ratio                  0
Ka/d Ratio                 0
Win %                      0
Kills per Game             0
Eliminations per Game      0
Damage per Game            0
Healing per Game           0
Eliminations per Min       0
Healing per Min            0
Damage per Min             0
Solo Kills                 0
Objective Kills            0
Final Blows                0
Damage Done                0
Eliminations               0
Environmental Kills        0
Multi Kills                0
Deaths                     0
Environmental Deaths       0
Games Won                  0
Games Played               0
Time Spent On Fire         0
Objective Time             0
Time Played                0
Assists                    0
Healing Done               0
Defensive Assists          0
Offensive Assists          0
Most Eliminations          0
Most Final Blows           0
Most Damage Done           0
Most Healing               0
Most Defensive Assists     0
Most Offensive Assists     0
Most Objective Kills       0
Most Objective Time        0
Most Solo Kills            0
Most Time Spent On Fire    0
Cards                      0
Medals                     0
Gold Medals                0
Silver Medals              0
Bronze Medals              0
Hero1                      0
Hero2                      0
Hero3                      0
Hero4                      0
Hero5                      0
dtype: int64

In [30]:
df.head()

,Battle_Tag,Level,Skill Rating,K/d Ratio,Ka/d Ratio,Win %,Kills per Game,Eliminations per Game,Damage per Game,Healing per Game,...,Cards,Medals,Gold Medals,Silver Medals,Bronze Medals,Hero1,Hero2,Hero3,Hero4,Hero5
0,Morellio-1416,"2,999","1,297,591,865",1.48,2.26,50.7%,14.21,14.21,"5,237.64","2,307.95",...,43.0,276,72,100.0,104.0,Mercy,Reinhardt,Orisa,Moira,Winston
1,Zinux-1251,422,"29,053,161",4.68,5.32,76.7%,33.84,33.84,"15,140.02","1,262.35",...,31.0,137,80,34.0,23.0,Hanzo,Ana,Torbjörn,Soldier: 76,Lúcio
2,BluePillow-21338,625,"28,042,860",2.33,2.72,80.0%,25.33,25.33,"9,547.33",886.13,...,5.0,31,12,12.0,7.0,Hanzo,Genji,Widowmaker,McCree,Tracer
3,Miyuna-21516,57,"25,273,056",2.71,2.96,70.0%,22.80,22.80,"7,987.43",578.83,...,0.0,67,12,21.0,34.0,Widowmaker,Reinhardt,Pharah,Genji,Hanzo
4,Mood-21538,459,"25,382,447",2.01,2.84,34.2%,18.66,18.66,"7,424.13","1,861.95",...,7.0,72,20,30.0,22.0,Widowmaker,Tracer,Hanzo,Ana,Zenyatta